services:
  frontend:
    container_name: frontend
    build: ./apps/frontend
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - "./apps/frontend:/app"
    depends_on:
      - dynamodb-local
    networks:
      - app-network

  backend:
    container_name: backend
    build: ./apps/backend
    command: dotnet watch --urls "http://0.0.0.0:5123"
    ports:
      - "5123:5123"
    volumes:
      - "./apps/backend:/app"
    depends_on:
      - dynamodb-local
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=testkey
      - AWS_SECRET_ACCESS_KEY=testsecret
    networks:
      - app-network

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./apps/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - app-network

  dynamodb:
    image: "aaronshaf/dynamodb-admin"
    container_name: dynamodb-admin
    depends_on:
      - dynamodb-local
    restart: always
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-east-1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
