version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm ci --cache .npm --prefer-offline
        build:
          commands:
            - echo -e "AUTH0_BASE_URL=$AUTH0_BASE_URL" >> .env.production
            - echo -e "AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID" >> .env.production
            - echo -e "AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET" >> .env.production
            - echo -e "AUTH0_ISSUER_BASE_URL=$AUTH0_ISSUER_BASE_URL" >> .env.production
            - echo -e "AUTH0_SECRET=$AUTH0_SECRET" >> .env.production
            - echo -e "AUTH0_AUDIENCE=$AUTH0_AUDIENCE" >> .env.production
            - echo -e "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL" >> .env.production
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - "**/*"
      cache:
        paths:
          - .next/cache/**/*
          - .npm/**/*
    appRoot: apps/frontend
